spring:
  data:
    mongodb:
      uri: "mongodb+srv://morri:1234@morri.pgsqs.mongodb.net/?retryWrites=true&w=majority&appName=morri"
      database: Morri

JWT:
  secret: "abcdefghijklmnopqrstuvwxyz123456"
  expiration: 86400000